# Argo CD Project for Staging Environment
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: launchpad-staging
  namespace: argocd
spec:
  description: Launchpad Staging Environment

  sourceRepos:
    - 'https://github.com/*/launchpad'
    - 'https://github.com/*/launchpad.git'

  destinations:
    - namespace: launchpad-staging
      server: https://kubernetes.default.svc

  # More restrictive for staging
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler

  roles:
    - name: deployer
      description: Can deploy applications
      policies:
        - p, proj:launchpad-staging:deployer, applications, sync, launchpad-staging/*, allow
        - p, proj:launchpad-staging:deployer, applications, get, launchpad-staging/*, allow
      groups:
        - deployers

    - name: readonly
      description: Read-only access
      policies:
        - p, proj:launchpad-staging:readonly, applications, get, launchpad-staging/*, allow
      groups:
        - viewers
